### ISSUE TITLE
Username and Password Validation Points

### ISSUE THREAD

**Issue by dehewune** [jinasenainfotech/JICSRD_Sprint1_Intenal#37]
**Password Policy**
- [ ] Password must be in between 6 and 16
- [ ] Must contain at least one Upper Case letter, one Lower case letter, one number and one special char

**Username Policy**
- [ ] Must not contain only numbers
- [ ] Must not contain any spaces

**Comment by shanilaSjayakody** [comment]
Must contain at least one Upper Case letter, one Lower case letter, one number and one special char 
* this should show at once not separately when i enter the password.
