### ISSUE TITLE
Report: API Data are not populating to the Report

### ISSUE THREAD

**Issue by dehewune** [jinasenainfotech/JICSRD_Sprint1_Intenal#44]
Please take the API based stored data to the report using the metadata provided.

**Comment by lkeranga** [comment]
This issue has been fixed

**Comment by dehewune** [comment]
> This issue has been fixed

Credit Score Indicator bar is not printed in the report. The rest of the API data are showing correctly.
![image](https://user-images.githubusercontent.com/29775359/68523760-9b074c80-02e3-11ea-9d64-2721719aa6ba.png)

This Indicator should come under the Non-financial based credit score section... and based on the current credit score from API out of 850 fixed score.

**Comment by dehewune** [comment]
fixed by @lkeranga
