### ISSUE TITLE
Issue with fonts

### ISSUE THREAD

**Issue by shanilaSjayakody** [jinasenainfotech/JICSRD_Sprint1_Intenal#60]
There is a issue with 'L' and I in the report. 

![Capture9](https://user-images.githubusercontent.com/32037349/68548199-2f6ecd80-0410-11ea-96ca-50fa38100488.PNG)

If you think this is something with my pc fonts. let me know

![Capture10](https://user-images.githubusercontent.com/32037349/68548598-a4440680-0414-11ea-8c05-bfee3648a4a1.PNG)

**Comment by shanilaSjayakody** [comment]
This is something with my pc since i'm running the web application localhost.

**Comment by shanilaSjayakody** [comment]
After I print the PDF i get the same error. We have to overcome this issue

**Comment by dehewune** [comment]
fixed by @lkeranga and @shanilaSjayakody
