### ISSUE TITLE
Wrong Calculations - Urgent

### ISSUE THREAD

**Issue by shanilaSjayakody** [jinasenainfotech/JICSRD_Sprint1_Intenal#65]
These fields gives the wrong calculations in data input screen. I have tested these values using the excel test case RIVALEA HOLDINGS PTY LTD   3 years to  2018 _12 Oct 2019.

You can also check the values in company RIVALEA HOLDINGS PTY LTD. There are 3 approved entries related to this company.

These fields shows the wrong calculations : 
* Ebitda 
* Profit after tax
* Profit after tax and distribution
* Total current assets 
* Total assets 
*  Balance

**Comment by dehewune** [comment]
fixed by @lkeranga
