### ISSUE TITLE
Home: Create New Report without selecting Company Validation Required

### ISSUE THREAD

**Issue by dehewune** [jinasenainfotech/JICSRD_Sprint1_Intenal#69]
When clicking "Create New Report" without selecting a company, the page refreshes but no error is shown. Please stop refreshing the page and show an error saying "You need to select a company first"

OR

**If this is easier, we can disable the "Create New Button" when the option value is "Select New Report"**

**Comment by shanilaSjayakody** [comment]
Apply the same scenario to Find button
