### ISSUE TITLE
Report: Calculation Issues - Urgent

### ISSUE THREAD

**Issue by shanilaSjayakody** [jinasenainfotech/JICSRD_Sprint1_Intenal#74]
Here we have identified issues in the report. Find the zip file related to identified issues.
 
[CW _SERCO 4-with errors marked.zip](https://github.com/jinasenainfotech/JICSRD_Sprint1_Intenal/files/3851383/CW._SERCO.4-with.errors.marked.zip)

**Comment by shanilaSjayakody** [comment]
Arrow indicators issue is still not fixed therefore we need to get it done as soon as possible too

**Comment by dehewune** [comment]
Latest report generated with database update and still the rounding issue is there... (Report is only for 2016 for Serco)
[CW _ Report_1.4.pdf](https://github.com/jinasenainfotech/JICSRD_Sprint1_Intenal/files/3853321/CW._.Report_1.4.pdf)

**Comment by dehewune** [comment]
Rounding issue is still there even after the database update...
![image](https://user-images.githubusercontent.com/29775359/68978390-9e895f00-0820-11ea-8277-cf242ef247fb.png)

**Comment by dehewune** [comment]
Other Indicators entire section seems to be incorrect...
![image](https://user-images.githubusercontent.com/29775359/68978411-af39d500-0820-11ea-811d-faa2db1fcfdf.png)

**Comment by dehewune** [comment]
The database seems it is accepting decimals now but report does not show... 
![image](https://user-images.githubusercontent.com/29775359/68978805-d8a73080-0821-11ea-9048-0b92f63effbf.png)

**Comment by shanilaSjayakody** [comment]
Z score is not fixed but i'm closing the ticket. We will reopen this once we are confirmed with Z score visibility
